# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6062e3944208a596552638b2439d9a906c4654788c5bf703fad3b1430f34120c445333e3ad3bf39a72627ab282e9702d52fff9366b7cc449b9aa61efc1464636

test:
  secret_key_base: cdcee245dbefc4efedfb89f25c2e0dfbd8491da182a4968cb24642c61594c3ca5756192060a7ccae2c466b998237cfeeed892dc58f15f223bbbd956cecc5172b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
